development:
  adapter: postgresql
  encoding: unicode
  database: twillio_development
  pool: 5
  username: efraimmgon
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: twillio_test
  pool: 5
  timeout: 5000
  username: efraimmgon
  password:

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
  timeout: 5000
